params:
  cookbook_icons_credits: "
    Cast Iron Skillet by W Fully from [Noun Project](https://thenounproject.com/browse/icons/term/cast-iron-skillet/) (CC BY 3.0)


    Pressure Cooker by Mitchell Fong from [Noun Project](https://thenounproject.com/browse/icons/term/pressure-cooker/) (CC BY 3.0)


    Sous Vide by Walker B Milhoan from [Noun Project](https://thenounproject.com/browse/icons/term/sous-vide/) (CC BY 3.0)


    Mixer by Saeful Muslim from [Noun Project](https://thenounproject.com/browse/icons/term/mixer/) (CC BY 3.0)
    
    
    Food Processor by Symbolon from [Noun Project](https://thenounproject.com/browse/icons/term/food-processor/) (CC BY 3.0)
    "
